//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCours
    {
        public StudentCours()
        {
            this.StudentCourses1 = new HashSet<StudentCours>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ICollection<StudentCours> StudentCourses1 { get; set; }
        public virtual StudentCours StudentCours1 { get; set; }
    }
}
